name: eng_alaa_hammed
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_localizations:
    sdk: flutter
  intl:
  flutter_bloc:
  logger:
  shared_preferences:
  dio:
  dartz:
  equatable:
  get_it:
  video_player:
  youtube_player_flutter:
  cached_network_image:
  google_sign_in:
  flutter_dotenv:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints:
  bloc_test:
  mocktail:

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
        - asset: assets/fonts/static/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/static/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/static/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/static/Cairo-Black.ttf
          weight: 900
